matrix:
  include:
    - language: python
      python: 3.6
      sudo: required
      install:
        - apt-get install libmesa-dev
        - python -m pip install pip wheel setuptools numpy -U
      script:
        - python setup.py develop

    - language: python
      python: pypy3.5
      install:
        - apt-get install libmesa-dev
        - python -m pip install pip wheel setuptools numpy -U
      script:
        - python setup.py develop

    - language: python
      python: 3.6
      sudo: required
      services:
        - docker
      script:
        - python3 setup.py sdist -d extras/docker-build
        - cd extras/docker-build && docker build .
