notifications:
  email: false

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - export TRAVIS=True
        # - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
        - python -m pip install pip wheel setuptools numpy -U
      script:
        - python setup.py develop

    - language: python
      python: pypy3.5
      script:
        - export TRAVIS=True
        - python setup.py develop

    - sudo: required
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_i686 linux32 sh /io/extras/build-travis/build.sh

    - sudo: required
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 sh /io/extras/build-travis/build.sh
