notifications:
  email: false

language: python
python:
  - 3.6

env:
  - TRAVIS=True

install:
  - python -m pytest -m before_build
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - python -m pip install -r tests/requirements.txt
  - python extras/gltraces/setup.py develop
  - python setup.py develop
  - python tests/print_info.py

script:
  - python -m pytest
