language: generic

sudo: false

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - os: linux
      language: python
      python: 3.4
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: linux
      language: python
      python: 3.5
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: linux
      language: python
      python: 3.6
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - python -m pip install pytest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - python -c "from distutils import sysconfig; import json; print(json.dumps(sysconfig.get_config_vars(), indent=4))"
  - python -m pip install -r tests/requirements.txt
  - python setup.py build_ext --inplace
  - python -m pip install -e .

script:
  - python -m moderngl
  - python -m pytest tests/test_local.py tests/test_module_integrity.py tests/test_pep8.py tests/test_documentation.py
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python -m pytest; fi
