notifications:
  email: false

language: python
python:
  - 3.6

install:
  - python --version
  - python -c "import sys; print(sys.version)"
  - gcc --version
  - g++ --version
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - python -m pip install pytest numpy
  - python setup.py develop
  - python test.py

script:
  - python -m pytest
