notifications:
  email: false

language: python
python:
  - 3.6

install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - python -m pip install pytest numpy
  - python setup.py develop
  - python tests/print_info.py

script:
  - python -m pytest
