language: python

sudo: true

matrix:
  fast_finish: true

python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - CC=gcc-4.8 CXX=g++-4.8 python setup.py build_ext --inplace
#  - python setup.py install

script: python setup.py install
