language: python

os:
  - linux
#  - osx

notifications:
  email: false

sudo: false

matrix:
  fast_finish: true

python:
  - 3.6
  - 3.5
  - 3.4

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-4.8
#       - g++-4.8

install:
  - python -c "import sys; print(sys.version, sys.platform)"
  - python setup.py build_ext --inplace
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - pip install -e .

#  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.4" ]; then pip install typing; fi
#  - python setup.py install

script:
  - python -m ModernGL
  - python -m pytest tests/module

#  - python -m ModernGL --info
